services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Secret@123
    ports:
      - "1433:1433"
    volumes:
      - noteapp_mssql:/var/opt/mssql

volumes:
  noteapp_mssql:
    driver: local