services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_DATABASE=notedb
      - MSSQL_SA_PASSWORD=Secret@123
    ports:
      - "1433:1433"
    volumes:
      - noteapp_mssql:/var/opt/mssql
    networks:
      - noteapp_csharp
    restart: always


  webapi:
    build:
      context: ./WebApi
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=notedb;User Id=sa;Password=Secret@123;TrustServerCertificate=True
    depends_on:
      - db
    networks:
      - noteapp_csharp
    restart: always

  frontsite:
    build:
      context: ./FrontSite
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - webapi
    networks:
      - noteapp_csharp
    restart: always

networks:
  noteapp_csharp:
    driver: bridge

volumes:
  noteapp_mssql:
    driver: local